---
- hosts: all
  sudo: yes
  gather_facts: no

  tasks:

  - name: install ntp
    yum: name=ntp state=installed update_cache=yes

  - name: write our ntp.conf
    copy: src=/home/vagrant/files/ntp.conf dest=/etc/ntp.conf mode=644 owner=root group=root
    notify: restart ntpd

  - name: start ntpd
    service: name=ntpd state=started

  handlers:

  - name: restart ntpd
    service: name=ntpd state=restarted
