---

# common
- hosts: all
  sudo: yes
  gather_facts: no

  tasks:

  - name: install git
    yum: name=git state=installed update_cache=yes

# web
- hosts: web
  sudo: yes

  tasks:

  - name: install nginx
    yum: name=nginx state=installed

  - name: add group www-data
    group: name=www-data state=present
    notify: restart nginx

  - name: add user www-data
    user: name=www-data shell=/bin/nologin groups=www-data,root append=yes
    notify: restart nginx

  - name: make sites-available folder
    file: path=/etc/nginx/sites-available state=directory owner=root group=root mode=0755
    notify: restart nginx

  - name: write our nginx.conf
    template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify: restart nginx
  
  - name: write our /etc/nginx/sites-available/default
    template: src=templates/default-site.j2 dest=/etc/nginx/sites-available/default
    notify: restart nginx

  - name: deploy website content
    template: src=templates/index.html.j2 dest=/usr/share/nginx/html/index.html

  handlers:

  - name: restart nginx
    service: name=nginx state=restarted

# lb
- hosts: lb
  sudo: yes  

  tasks:

  - name: install haproxy and socat
    yum: pkg={{ item }} state=latest
    with_items:
    - haproxy
    - socat

  - name: make file /etc/default/haproxy
    file: path=/etc/default/haproxy state=touch owner=root group=root mode=0640

  - name: enable haproxy
    lineinfile: dest=/etc/default/haproxy regexp="^ENABLED" line="ENABLED=1"
    notify: restart haproxy 

  - name: deploy haproxy config
    template: src=templates/haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg
    notify: restart haproxy

  handlers:

  - name: restart haproxy
    service: name=haproxy state=restarted
